version: '3.8'

services:
  postgres:
    image: postgres:15
    ports:
    - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: user
      POSTGRES_USER: postgres
      POSTGRES_DB: forecast
volumes:
    db_data: